### ISSUE TITLE
Integration with WordPress

### ISSUE THREAD

**Issue by quicoto** [sindastra/CPPaste4#4]
*Feature Request*

I wonder if we could integrate this with WordPress, somehow. Pasting the link into Gutenberg's editor could embed the code directly on the WordPress post/page.

![WordPress](https://cloudup.com/cfnHUgyGiAM+)

**Comment by sindastra** [comment]
Thanks for the suggestion! I will take a look.

**Comment by sindastra** [comment]
WordPress seems to use oEmbed for the most part, so that's what I would have to integrate.

- https://oembed.com/

But sadly there's no point to it because as stated by WordPress ["will only embed URLs matching an internal whitelist."](https://wordpress.org/support/article/embeds/#does-this-work-with-any-url)
